// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaoO2gaoGkr_u0ZlHWCe-eM-fDXBRFjpQ',
    appId: '1:976432364652:web:f11cd902f4b2bd7887ec49',
    messagingSenderId: '976432364652',
    projectId: 'traning-beta',
    authDomain: 'traning-beta.firebaseapp.com',
    storageBucket: 'traning-beta.appspot.com',
    measurementId: 'G-0JD2C5QDZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP731AAtuzE-OR0NaIZmjV2B8EXBlOqmE',
    appId: '1:976432364652:android:7ebb3af152928d2d87ec49',
    messagingSenderId: '976432364652',
    projectId: 'traning-beta',
    storageBucket: 'traning-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_TeSpok1EaxeRESu5jr0gHUtxs0YOYq8',
    appId: '1:976432364652:ios:013dff9f0850edad87ec49',
    messagingSenderId: '976432364652',
    projectId: 'traning-beta',
    storageBucket: 'traning-beta.appspot.com',
    iosBundleId: 'com.example.traningBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_TeSpok1EaxeRESu5jr0gHUtxs0YOYq8',
    appId: '1:976432364652:ios:013dff9f0850edad87ec49',
    messagingSenderId: '976432364652',
    projectId: 'traning-beta',
    storageBucket: 'traning-beta.appspot.com',
    iosBundleId: 'com.example.traningBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaoO2gaoGkr_u0ZlHWCe-eM-fDXBRFjpQ',
    appId: '1:976432364652:web:5fae33f7761ce1c187ec49',
    messagingSenderId: '976432364652',
    projectId: 'traning-beta',
    authDomain: 'traning-beta.firebaseapp.com',
    storageBucket: 'traning-beta.appspot.com',
    measurementId: 'G-NS1JVD2DGX',
  );
}
